#!/bin/sh


SCRIPT="java -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -Xmx50m -jar $INSTALL_PATH/$APP_NAME-$VERSION.jar"



PIDFILE="/var/run/$APP_NAME.pid"
LOGFILE="/var/log/$APP_NAME/service.log"

[ -f "$INSTALL_PATH/env" ] && . "$INSTALL_PATH/env"

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE") &> /dev/null; then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

status() {
  if [ -f "$PIDFILE" ] || kill -0 $(cat "$PIDFILE"); then
    echo "Service $APP_NAME is running" >&2
  else
    echo "Service $APP_NAME is not running" >&2
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
